### ISSUE TITLE
dependencies with optional dependencies are not properly resolved.

### ISSUE THREAD

**Issue by vrozov** [siom79/japicmp#125]
for example dependency on com.ning:async-http-client:1.7.x leads to an error due to it's optional dependencies on com.google.guava:guava.

**Comment by siom79** [comment]
Optional dependencies are according to the [documentation](https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html) only normal dependencies in the pom where they are defined. In your example guava is only a normal dependency within async-http-client. Projects that depend on async-http-client do not resolve this optional dependency. Hence it should be correct that the dependency on guava gets not resolved if it is declared to be optional for async-http-client.

What error do you get?

**Comment by vrozov** [comment]
adding async-http-client as a dependency to dependencies section of japicmp maven plugin results in async-http-client dependency not being resolved error.

**Comment by siom79** [comment]
According to my understanding of optional dependencies `guava` should be added to the dependency section of your project.

**Comment by vrozov** [comment]
No, it should not. It should work exactly the same as if async-http-client was added as a dependency to the project pom.

**Comment by siom79** [comment]
But `async-http-client` declares `guava` as optional. Hence modules using `async-http-client` should not import it.

The idea behind optional dependencies is that if you implement a facade for let's say different database projects, than you declare the dependencies in your facade project on the different database vendors as optionals. Clients to your facade project do only add the dependency they acutally need (e.g. H2 and not MySql, Oracle, etc.) and don't import all optional ones.

But I could change japicmp that one can configure to also include optional dependencies. But then all optional dependencies are pulled in. But what if you don't have access to a specific optional dependency because it resides on a repository you don't have access to? 

And when I make it configurable that you can choose which optional depencendies to pull in, then it is the same as if you would add the optional dependency to your project.

**Comment by vrozov** [comment]
This is exactly how optional dependency should work. Problem is that when I include a dependency with optional dependencies into `<dependencies>` section of japicmp the entire build fails.

**Comment by siom79** [comment]
OK. Thanks for the details regarding `dependencies` section of japicmp itself. 

The dependencies listed here are resolved by japicmp and it checks that all dependencies could be resolved properly. Otherwise japicmp threw an exception. As I configured the `ArtifactResolutionRequest` to skip optional dependencies, I thought it would not return them. But as I have now seen it will return the `Artfact` object but with `getFile()` returning nothing. This led the code throw an exception because not all dependencies could be resolved properly.

I have now introduced a check if the `Artfact` was optional that in this case I don't expect `getFile()` to return something useful.
