### ISSUE TITLE
Maven plugin missing parameter `html-file`

### ISSUE THREAD

**Issue by bdemers** [siom79/japicmp#178]
Possibly just a `fileName` parameter that can be applied to all the report formats

- target/japicmp/default-cli.diff
- target/japicmp/default-cli.xml
- target/japicmp/default-cli.html

**Comment by siom79** [comment]
If you specify an execution id, it is used as file name:

```
<plugin>
	<groupId>com.github.siom79.japicmp</groupId>
	<artifactId>japicmp-maven-plugin</artifactId>
	<version>0.10.0</version>
	<executions>
		<execution>
			<id>normal</id>
[...]
```
Have you tried this?

**Comment by bdemers** [comment]
I never would have guessed that, thanks!

**Comment by Marcono1234** [comment]
Could you please add a parameter to explicitly specify the file name as well?

For example for a multi-module Maven project it might be convenient to only specify the japicmp configuration once for the parent project, then use something like `<fileName>${project.artifactId}</fileName>` (assuming that is how such a parameter would be named) and from the command line run `mvn japicmp:cmp`.
With the current approach of using the execution ID, I assume this is not easily possible because the IDs would differ for each Maven module of the project.
