### ISSUE TITLE
Maybe add jaxb-api as a dependency

### ISSUE THREAD

**Issue by io7m** [siom79/japicmp#183]
Hello.

I've been looking into what it'd take to remove the requirement for using `MAVEN_OPTS` on JDK 9. I first assumed that I'd need to write actual module descriptors in order to specify an explicit dependency on the `java.xml.bind` module, but ran into a lot of problems related to Maven. Instead, Robert Scholte (Maven developer) recommended that the following dependency be added to the Maven plugin instead:

```
<dependency>
     <groupId>javax.xml.bind</groupId>
     <artifactId>jaxb-api</artifactId>
     <version>2.3.0</version>
</dependency>
```

That should eliminate the need for `MAVEN_OPTS`.

I would test this, but I'm still having trouble building the project on JDK 9. It seems that there's a `java.lang.ArrayIndexOutOfBoundsException` raised by the version of ASM used by the `maven-plugin-plugin`. I suspect it's just a case of upgrading to a newer version. I'm currently experimenting with bringing up all plugin versions to their latest version in a fork, but I'm not sure if you're specifically sticking to older versions of any of them in order to maintain Java 7 compatibility.

**Comment by siom79** [comment]
Adding only the jaxb-api dependency does cause the following exception:
```
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122)
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276)
	... 29 more
```
Also when I add additionally the jaxb-runtime from glassfish, I get the following error: `java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.annotation.AnnotationReader`.

I know that I can add a `module-info.java` file and declare a dependency on `java.xml.bind`, but then I need to add also dependencies on guava and javassist. As both are currently not published as Java 9 modules, I should not release japicmp as long as I have unnamed dependencies (that is what I understood so far). Beyond that adding a `module-info.java` also requires to set source and target version to 1.9 for the compiler plugin. Therewith I also loose 1.7 compatibility.

So currently I only see the option of having `--add-modules java.xml.bind` in the `MAVEN_OPTS`.

**Comment by io7m** [comment]
It's a shame, but it's understandable. I get the feeling that JPMS and Maven's older internal module system don't play well with each other.

**Comment by twogee** [comment]
I'm quite sure JPMS has taken Maven into account [1]. Unfortunately, I cannot point to final specs 😞 

[1] http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html

**Comment by io7m** [comment]
To be clear, I'm referring to Maven's internal module system, Plexus:

https://codehaus-plexus.github.io/

Not the Maven modules that users of Maven are exposed to (when creating multi-module projects and so on).

**Comment by ansell** [comment]
The ``java.xml.bind`` JVM module is deprecated with the ``forRemoval`` flag set to ``true``, so just adding it from the JVM module set isn't a final solution, even after javassist and guava release modularised versions.

https://docs.oracle.com/javase/9/docs/api/java.xml.bind-summary.html

The migration path still seems to be to use the jaxb-api module along with an implementation of choice. 

In regards to the issues referred to above with using the latest 2.3.0 version of that, the repository for it (including the reference implementation) seems to be:

https://github.com/javaee/jaxb-v2

Looking through that code, in particular the following line, it appears that there may still be some trickery involved with replacing the deprecated JVM module with the reference implementation using upgrade-module-path:

https://github.com/javaee/jaxb-v2/blob/master/jaxb-ri/runtime/impl/pom.xml#L120

However, in either case, it would be great if this issue could be reopened until the issue is fully understood for japicmp users, preferably with a final solution that doesn't include adding the deprecated module to their module path if possible.

**Comment by twogee** [comment]
Ah, JAXB is moving into Java EE...

It seems that the missing dependency is [core](https://stackoverflow.com/questions/27046836/why-has-annotationreader-been-removed-from-jaxb-reference-implementation)
```
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.3.0</version>
</dependency>
```
Yet according to POM, runtime has core as its dependency...

**Comment by siom79** [comment]
@twogee:

Using the dependency mentioned in your last post leads to the following results on my machine (with Oracle JDK 9.0.1+11):
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 55297
	at org.objectweb.asm.ClassReader.readClass(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
```
The same is true when I use the following dependency:
```
<dependency>
	<groupId>org.glassfish.jaxb</groupId>
	<artifactId>jaxb-runtime</artifactId>
	<version>2.3.0</version>
</dependency>
```
It looks like the [maven-plugin-plugin](https://maven.apache.org/plugin-tools/maven-plugin-plugin/) causes this exception. But even the newest version 3.5.2 produces the same error.

@ansell 

The official [Oracle Migration Guide for Java 9](https://docs.oracle.com/javase/9/migrate/toc.htm#JSMIG-GUID-F640FA9D-FB66-4D85-AD2B-D931174C09A3) says that `javax.xml.bind` has been introduced as module but at the same time marked as deprecated because they want to move its content out of the JDK into Java EE. But they say also:

> Use the --add-modules command-line option to ensure that the module with the API is resolved at startup. For example, specify --add-module java.xml.bind to ensure that the java.xml.bind module is resolved. This allows existing code that uses the JAXB API and implementation to work as it did in JDK 8.
> This is a temporary workaround because eventually these modules will be removed from the JDK.

They further say:

> Deploy the standalone version of the API (and implementation if needed) on the class path. Each of the Java EE APIs are standalone technologies with projects published in Maven Central.

The [User Guide for JAX-B](https://javaee.github.io/jaxb-v2/doc/user-guide/ch03.html#running-on-java-9) mentions with regard to usage with Java 9:

> Bundled version in Java SE can be used by adding java.xml.bind / jdk.xml bind to module graph, e.g. depending on those modules if application is loaded as JPMS module, or adding them with command line --add-modules java.xml.bind,jdk.xml.bind
> In order to use standalone version of JAXB, java.xml.bind should be upgraded with jaxb-api module. Implementation jars jaxb-core and jaxb-impl are not modularized yet and should be placed on classpath to be run as unnamed module.

Beyond that you see that the jax-b team also includes the module `java.xml.bind` to [compile](https://github.com/javaee/jaxb-v2/blob/master/jaxb-ri/runtime/impl/pom.xml#L120) their sources on a JDK 9.

From these guides I would summarize that the `javax.xml.bind` module will be removed in future versions from the JDK (as it then is only part of the Java EE). But until then the option `--add-modules` is a valid workaround, especially if your build fails with exceptions when using the Java EE version of the bundle.

**Comment by twogee** [comment]
This exposes the state of Maven plugins... Running `mvn -X` I can see ASM 6.0_BETA, 5.0.2, 4.1 and 3.3.1 in the log. None of those versions has full support of Java 9.

**Comment by twogee** [comment]
Although it seems that the problem with jaxb-core might be caused by [pre-v5 ASM](https://stackoverflow.com/questions/35046404/arrayoutofboundsexception-asm-classreader-readclassunknown-source)

**Comment by io7m** [comment]
Quite a few Maven plugins are waiting for releases of the [maven-shared](https://github.com/apache/maven-shared) components that fix a lot of these issues.

**Comment by ansell** [comment]
Sorry, yesterday I was confused about the way that JEE were compiling jaxb-ri. The use of upgrade-module-path is the key to them not using the deprecated JSE module anymore and replacing it with their local version, which is not deprecated. My bad.

**Comment by mattnworb** [comment]
Hey, I am trying to build a project on jdk11 that uses this plugin and I ran into the same problem mentioned above.

I found that adding the following dependencies to the `<plugin>` in my pom.xml, when building with the maven docker image `maven:3.5.4-jdk-11-slim` seems to resolve issues:

```
--- a/pom.xml
+++ b/pom.xml
@@ -99,6 +99,23 @@
                             </goals>
                         </execution>
                     </executions>
+                    <dependencies>
+                      <dependency>
+                        <groupId>org.glassfish.jaxb</groupId>
+                        <artifactId>jaxb-core</artifactId>
+                        <version>2.3.0</version>
+                      </dependency>
+                      <dependency>
+                        <groupId>org.glassfish.jaxb</groupId>
+                        <artifactId>jaxb-runtime</artifactId>
+                        <version>2.3.0</version>
+                      </dependency>
+                      <dependency>
+                        <groupId>javax.activation</groupId>
+                        <artifactId>javax.activation-api</artifactId>
+                        <version>1.2.0</version>
+                      </dependency>
+                    </dependencies>
```

Sounds like perhaps the issues with maven plugins mentioned above have since been addressed, if one is using a modern maven?

**Comment by twogee** [comment]
+1 for reviewing JAXB dependencies (see #177, too). According to [release notes](https://javaee.github.io/jaxb-v2/doc/user-guide/ch02.html#a-2-3-0), the correct version of JAXB for Java 9+ is 2.3.0
