### ISSUE TITLE
Show semver difference

### ISSUE THREAD

**Issue by eldur** [siom79/japicmp#26]
As developer I want to know a short info about api changes - as lib maintainer I want check the compatibility with previous jar without details.

* When I call ```java -jar japicmp.jar --old .. --new .. --only-semver-diff``` the output is one of the following values:  ```1.0.0``` or ```0.1.0``` or ```0.0.1```

```1.0.0``` means: there are incompatible (```-b```) public (```-a public```) changes like method deletions 
```0.1.0``` means: there are public (```-a public```) changes like new methods or classes
```0.0.1``` means: there are **no** public (```-a public```) changes

* Compatible switches for ```--only-semver-diff``` are ```--exclude, --include, --new, --old```

The output of this call can be interpreted like ```output = newVersion - oldVersion```.

See also: http://semver.org/

(I know that semver addresses also internal behavior and not only api changes, but I think it is a helpful short information. - I don't want to work with given maven pom versions.)

**Comment by eldur** [comment]
What do you think about the changes?

**Comment by siom79** [comment]
I like the idea of pointing the user to the position in the version that has to be incremented and also appreciate your work. :)

Meanwhile I had a quick look at your implementation:
* Initially the command `mvn clean install` failed under Windows, because the following line does not use `File.separator`: `assertThat(root.getAbsolutePath(), new StringEndsWith("/japicmp-testbase/japicmp-test/."));`
* We should reuse code wherever possible. Hence we can use `Helper.getArchive()` instead of the new method `Helper.getArchiveLike()` or refactor `Helper.getArchive()`accordingly (although I don't see the necessity to have a like operator in this case).
* The idea to filter the archive with package names for detecting only certain changes is good. But please name the methods you use such that the name indicates what will happen, like for example `returnValueChangesFromVoidToString()` instead of `doAll()`. That helps understanding what is going on a lot. And please also remove methods that do not affect the result (like e.g. `doSomething()` in `SemverTestee010b`).
* Why do you use two subpackages `a` and `b`?

**Comment by eldur** [comment]
1,2) I'll see what I can do with the Helper methods
3,4) mehtods with names "doAll" or "doSomething" are only testmethods without any sense. I created them in the ```*Testee*``` classes to give japicmp some food at different visiblity levels. The packages ```a``` and ```b``` are used for different test cases - check ```SemverOutIntegTest``` for details. It is no problem for me to rename ```public void doNothing()``` in ``` SemverTestee100a``` to ```public void senslesPublicMethodOnlyForTesting()``` ... should I? (I hoped to use such strange names will indicate that thay have no sense :wink: )

**Comment by siom79** [comment]
Taking a closer look at SemverOut, I am not sure if the implementation is sufficient as the notion of binary compatibility is more than a modification. 

Take for example section [13.4.7](http://docs.oracle.com/javase/specs/jls/se7/html/jls-13.html#jls-13.4.7) of the Java Language Specification. Just changing an access modifier from public to package protected may also cause binary incompatibility.

As I understand the document [Semantic Versioning](http://semver.org/), then a bug fix that increments the patch version, changes only internal behavior. Hence we cannot detect it.

We can detect changes in the minor version: Any modification but no binary incompatible one. 

We can also detect changes in the major version: Modifications that are binary incompatible.

**Comment by eldur** [comment]
I've configured the access modifier to public and marked [removal](https://github.com/eldur/japicmp/commit/a1a4f03a12894e35fa7bc3fdf7d63e53b5388697#diff-87730af47816832fd75aafaff3b81ac7R107) as major change. But I'll add new testcase for that case.

**Comment by siom79** [comment]
Implementing what I have written above, the code should look like this (to my understanding of [Semantic Versioning](http://semver.org/):

```
	static SemverStatus signs(JApiHasChangeStatus hasChangeStatus) {
		JApiChangeStatus changeStatus = hasChangeStatus.getChangeStatus();
		switch (changeStatus) {
		case UNCHANGED:
			return SemverStatus.UNCHANGED;
		case NEW:
		case REMOVED:
		case MODIFIED:
			if (hasChangeStatus instanceof JApiBinaryCompatibility) {
				JApiBinaryCompatibility binaryCompatibility = (JApiBinaryCompatibility) hasChangeStatus;
				if (binaryCompatibility.isBinaryCompatible()) {
					return SemverStatus.CHANGED_BINARY_INCOMPATIBLE;
				} else {
					return SemverStatus.CHANGED_BINARY_COMPATIBLE;
				}
			}
		default:
			throw new IllegalStateException();
		}
	}
```
and
```
		if (build.contains(SemverStatus.CHANGED_BINARY_INCOMPATIBLE)) {
			return "1.0.0";
		} else if (build.contains(SemverStatus.CHANGED_BINARY_COMPATIBLE)) {
			return "0.1.0";
		} else if (build.isEmpty() || build.contains(SemverStatus.UNCHANGED)) {
			return "0.0.1";
		} else {
			return "N/A";
		}
```

(sorry for copying it here, but unfortunately I cannot fork your repository back :) )

**Comment by eldur** [comment]
I'm not very familiar with binary compatibility at this level, I thought a removal from public API must be incompatible. In case of an new method you are right, this could be result in incompatibility.

If you want to change something, I'll suggest: accept the change (maybe another branch) -- I'm only working on the classes ```Helper``` and ```SemverOutIntegTest``` .. I'll create an new pull request for them.

**Comment by eldur** [comment]
btw: do you have a testcase where a new field causes an binary incompatibility without any removal?

**Comment by siom79** [comment]
Have a look at this class [here](https://github.com/siom79/japicmp/blob/master/japicmp-testbase/japicmp-test/src/test/java/japicmp/test/BinaryCompatibilityTest.java#L99).

**Comment by eldur** [comment]
I hope this is enough (I don't know why travis fails - locally ```mvn test``` returns ```BUILD SUCCESS``` - can you help or retrigger)?. About the topic ```Helper.archiveLike```: all tests with ```Helper.archive``` does not work with my IDE / only with ```mvn test``` so I added the new version.

**Comment by siom79** [comment]
When running the tests within the IDE you have to pay attention to the "working directory". Set this to `japicmp-testbase/japicmp-test` as the file paths in the test have to be relative to the module directory. Otherwise the maven build would fail.

**Comment by eldur** [comment]
I've seen you closed my pull request without a comment. Does this mean you will rebase and merge the change manually?

**Comment by eldur** [comment]
btw: my working directory seems to be correct but the file ```japicmp-testbase/japicmp-test/target/japicmp-test-v1.jar``` was not found because its name is ```japicmp-testbase/japicmp-test-v1/target/japicmp-test-v1-0.2.3-SNAPSHOT.jar```

**Comment by siom79** [comment]
Sorry, I did not close your pull request intentionally. I have released yesterday evening the branch missed-changes and the branch was deleted afterwards. This caused the deletion of your pull request. Can you issue another one? Thank you in advance.

**Comment by eldur** [comment]
here it is

**Comment by siom79** [comment]
I have merged your pull request to the new branch `feature-semver`.

Unfortunately the maven build failed in `SemverOutIntegTest.testSemver100_superclass_with_field()`.

As mentioned above, from my point of view the method `Helper.getArchiveLike()` is not necessary. Changing that call to the existing `Helper.getArchive()` worked well (see travis-ci build).

**Comment by eldur** [comment]
I cannot reproduce the build failure on this branch - can you help me?

But I figured out the difference between ```Helper.getArchive()``` and ```Helper.getArchiveLike()```.

```Helper.getArchiveLike()``` will work at this level
```bash
~/git/japicmp (feature-semver u=)$ mvn clean package
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
~/git/japicmp (feature-semver u=)$ find . | egrep ".jar$"
...
./japicmp-testbase/japicmp-test-v1/target/japicmp-test-v1-0.2.4-SNAPSHOT.jar
...
./japicmp-testbase/japicmp-test-v2/target/japicmp-test-v2-0.2.4-SNAPSHOT.jar
...
```
```Helper.getArchive()``` requires a maven run up to integration-test
```bash
~/git/japicmp (feature-semver u=)$ mvn clean integration-test
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
~/git/japicmp (feature-semver u=)$ find . | egrep ".jar$"
...
./japicmp-testbase/japicmp-test-v1/target/japicmp-test-v1-0.2.4-SNAPSHOT.jar
...
./japicmp-testbase/japicmp-test/target/japicmp-test-v2.jar
./japicmp-testbase/japicmp-test/target/japicmp-test-v2-instrumented.jar
./japicmp-testbase/japicmp-test/target/japicmp-test-v1.jar
...
./japicmp-testbase/japicmp-test-v2/target/japicmp-test-v2-0.2.4-SNAPSHOT.jar
...
```
Personally I would prefer not to copy the test jars, but it's your project. If you prefer the copy way I'll suggest to throw an exception like "Please run integration test for the whole project before you run this test"

btw: do we need source and javadoc jars for ```japicmp-test-v1``` and ```japicmp-test-v2``` - I tend to disable its creation to reduce the buildtime ... ok?

**Comment by siom79** [comment]
I have taken a closer look at the test case and it turns out that the method `SemverOut.value()` modifies `options` and set the access modifier level to `public` ([reference](https://github.com/siom79/japicmp/blob/feature-semver/japicmp/src/main/java/japicmp/output/semver/SemverOut.java#L36)). This will filter out the new protected field `field`. As a result the set `build` is empty and the following switch return "0.0.1" instead of "1.0.0". 

But as I have mentioned before, it is not enough for binary compatibility to just look at public class members (see my suggested changes above).

Regarding the jar archives in japicmp-test, I have utilized the `maven-dependency-plugin` to pull in the two versions of this archive. This way the module japicmp-test is completely independent of the maven structure. Your implementation makes assumptions about the relative path to the other two modules.

I also configured the module such that the `maven-surefire-plugin` is executed in the `integration-test` phase. This way a simple `mvn test` on the `japicmp-test` module does not execute the junit tests, as they are written as a kind of integration test (testing the complete library with real archives and without mocking). So from my point of view everything is OK. ;-)

**Comment by eldur** [comment]
Ups you have changed something too ... maybe there are some useful parts in my pull request ... like the tests (your initial suggestion catches not all cases - in my point of view)

**Comment by eldur** [comment]
Sorry about rolling back your change "Rename Semver wording (major,minor,patch) to (UNCHANGED, CHANGED_BINARY_COMPATIBLE, CHANGED_BINARY_INCOMPATIBLE)" ... it was the easiest way to rebase my change.

**Comment by siom79** [comment]
I have taken a look at your new implementation of detect 'changeStatus()`. You can just take my suggested implementation above, it does not miss anything. You have added tests for public modifiers, but this is not necessary. A call to `isBinaryCompatible()` tells you whether this change is binary compatible or not. So if you add a new public method, `isBinaryCompatible()` will return `true`. If you modify a public member, it will return `false`, etc. Hence you do not have to do the additional checks in `changeStatusFromAccessModifier()`. From my point of view you can remove this method completely (and with it its tests).

Your pull request also destroys the renaming I have started yesterday in order to provide significant names to methods and fields under test.

**Comment by eldur** [comment]
No problem, feel free to abandon this patch ... I tried to understand and help :wink:

Should I transform my testcases to more integration tests or do you complete the issue #26 by yourself?

**Comment by siom79** [comment]
Of course, you can add some more integration tests. I will continue to do the renaming and will also add some tests.

**Comment by eldur** [comment]
I've seen you published the toggle "-s, --semantic-versioning" in current develop branch. Personally I tend to hide it because it doesn't work correct.

e.g. an annotation on an constructor causes (I assume ```!``` indicates binary incompatible) -- not sure
```
***! MODIFIED CLASS: PUBLIC Any
  ***  MODIFIED CONSTRUCTOR: PUBLIC Any(java.lang.String)
    +++  NEW ANNOTATION: java.lang.Deprecated
=> 1.0.0
```
Expected is ```0.1.0```

**Comment by siom79** [comment]
Thanks for pointing this out. The problem here is that the added annotation causes the constructor to become modified. But the constructor itself is not modified (we do not see any changes). The same is true for the class. It is flagged as modified and binary incompatible because it has one changed constructor. 

I have fixed this on the `develop` branch.

**Comment by eldur** [comment]
```
***! MODIFIED CLASS: PUBLIC Any
  ===  UNCHANGED CONSTRUCTOR: PUBLIC Any(java.lang.String)
    +++  NEW ANNOTATION: java.lang.Deprecated
==> 1.0.0
```
looks better but, the class is already modified

**Comment by siom79** [comment]
Is this only a snippet from the output, i.e. has the class other changes?

**Comment by eldur** [comment]
Yes only this 3 lines for the class, I try to create a test (But I assume you are faster)

**Comment by eldur** [comment]
(btw: where can I found the preferred indentation rules? I assume "indent with tab, line length 250")

**Comment by siom79** [comment]
Yes, indent with tab, line length 180.

**Comment by siom79** [comment]
I have created a class `Any` with one constructor `Any(java.lang.String)` and added in the second version the annotation `@Deprecated`. This is the output I get for `onlyModifications=true`:

```
===  UNCHANGED CLASS: PUBLIC japicmp.test.annotation.AnnotationAddedToConstructor
	===  UNCHANGED CONSTRUCTOR: PUBLIC AnnotationAddedToConstructor(java.lang.String)
		+++  NEW ANNOTATION: java.lang.Deprecated
```

**Comment by eldur** [comment]
I think this issue is complete. If I can reproduce this behavior, I'll open a new one
