### ISSUE TITLE
New static method in interface detected as METHOD_NEW_DEFAULT

### ISSUE THREAD

**Issue by runeflobakk** [siom79/japicmp#289]
I have added a couple of **public static** methods in an interface, and japicmp detects them as a binary incompatible `METHOD_NEW_DEFAULT` change. I don't have the knowledge to tell if this indeed is incompatible, but I was a bit surprised, and since the change indicates something to do with default methods, I thought I'd ask if this may be a false positive.

Should adding static methods to an interface be detected as `METHOD_NEW_DEFAULT`?

If I have not provided enough context here, please just let me know what information you need :)

<img width="1106" alt="report showing new static methods detected as METHOD_NEW_DEFAULT" src="https://user-images.githubusercontent.com/174823/122567951-83f51880-d049-11eb-969e-deb4bcd48f5a.png">

**Comment by WencongLiu** [comment]
Hello @runeflobakk , I meet a similar problem with you. The link is [ISSUE](https://github.com/siom79/japicmp/issues/361). The difference is that I set BinaryIncompatible to  disabled and SourceIncompatible to enabled.

However, I think adding a default method to an interface shouldn't be source incompatible. Do you have any solution right now?

**Comment by WencongLiu** [comment]
Thanks for your reply! @siom79  Looking forward to the next version.

**Comment by WencongLiu** [comment]
When will the next version be released, please? @siom79  😄

**Comment by siom79** [comment]
I have just released 0.17.3. It should be available in Maven central within a few hours.

**Comment by Marcono1234** [comment]
@siom79, it looks like this issue here was also about whether new `static` interface methods should be reported as `METHOD_NEW_DEFAULT`. Is that intended? japicmp 0.17.3 still behaves this way.

For regular classes, adding a `static` method seems to be reported as `METHOD_ADDED_TO_PUBLIC_CLASS`. Though there seems to be no corresponding existing type for interfaces yet; `METHOD_ADDED_TO_INTERFACE` seems to be about `abstract` interface methods.

**Comment by siom79** [comment]
@Marcono1234 Yes, you are right. If the method is new an not abstract (e.g. static) it is flagged as `METHOD_NEW_DEFAULT`. It should rather be flagged `METHOD_ADDED_TO_INTERFACE`. I need to change that.

**Comment by Marcono1234** [comment]
> It should rather be flagged `METHOD_ADDED_TO_INTERFACE`

Or would it need a new type? Because `METHOD_ADDED_TO_INTERFACE` is currently for adding an `abstract` method, which is not source compatible, while adding a `static` method is source compatible.

Should maybe `METHOD_ADDED_TO_INTERFACE` then also be deprecated and be renamed to <code>METHOD_<i>ABSTRACT</i>_ADDED_TO_INTERFACE</code> to be more precise and to match the name of the existing `METHOD_ABSTRACT_ADDED_TO_CLASS` type?

**Comment by siom79** [comment]
I have fixed the issue in the latest commit. In this context I have introduced three new incompatiblities:
- METHOD_NEW_STATIC_ADDED_TO_INTERFACE
- METHOD_NON_STATIC_IN_INTERFACE_NOW_STATIC
- METHOD_STATIC_IN_INTERFACE_NO_LONGER_STATIC
