### ISSUE TITLE
some newer kotlin changes show up as a binary string

### ISSUE THREAD

**Issue by hgschmie** [siom79/japicmp#370]
Thank you for japicmp! This is a great tool!

When comparing some kotlin classes, I got a report like this:

<img width="1447" alt="Screenshot 2024-01-20 at 09 27 11" src="https://github.com/siom79/japicmp/assets/39495/f0b556cc-f8d0-4fa2-b8e8-6592326bb73e">

This is with kotlin 1.6.21, kotlin plugin 1.9.22, kotlin api version compat to 1.6. I use JDK 21, compiling to JDK 11 compatibility. 

Let me know if you need more information; I am evaluating japicmp for a project and I can poke a various things if that helps track down the problem.

**Comment by siom79** [comment]
As far as I know the kotlin compiler introduces this annotation to classes in order to track some internal information. The format of the annotation seems to be defined [here](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/Metadata.kt). `d1` seems to be an array of String, but looks like some binary data here. For more details you must consult a Kotlin developer.

**Comment by hgschmie** [comment]
given that the plugin supports kotlin, shouldn't it either ignore the Metadata file (which seems to be internal and compiler generated) or show more comprehensive information?

**Comment by siom79** [comment]
Does japicmp support Kotlin? 😉 
As far as I know there is no comprehensive spec for the annotation. And what should be the use case? Its meaning should be transparent for the user.
