### ISSUE TITLE
Unnecessary hyperlinks in Markdown report

### ISSUE THREAD

**Issue by scordio** [siom79/japicmp#409]
I enabled the Markdown report in AssertJ and tested a binary incompatible change:

https://github.com/assertj/assertj/actions/runs/10551028776

Overall, I noticed that:
* All the badges have a link to https://camo.githubusercontent.com/
* Some elements in the details section point to https://github.com/assertj/assertj/actions/runs/10551028776#

See for example all the blue hyperlinks here:

![image](https://github.com/user-attachments/assets/8d65e860-b259-4acd-a5cd-950e01455b2c)

What do you think about removing such hyperlinks, as they don't add much value?

Thanks again for your work, @guillermocalvo, it looks very nice!

**Comment by guillermocalvo** [comment]
> - All the badges have a link to https://camo.githubusercontent.com/

Badges are generated as pure Markdown images. When GitHub renders a document, it [automatically caches images](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls) and adds links to their cached version.

I'm afraid there's nothing we can do about it; that's standard behavior. You can see it in action on your screenshot above, for which GH added a link to `https://private-user-images.githubusercontent.com/...`.

> - Some elements in the details section point to <https://github.com/assertj/assertj/actions/runs/10551028776#>

This, on the other hand, is an intentional *trick* to help make reports more concise.

While developing the Markdown generator, I noticed that the "Methods" table was easily bloated when there were many parameters, or when the package names were too long. This made the tables hard to read. So I decided to render *simple class names* instead of *fully qualified names*. But I didn't want to completely lose those FQNs.

So, for example:

| Constructor |
|---|
| `AbstractStringAssert`\([`String`](# "java.lang.String"), [`Class<?>`](# "java.lang.Class<?>")\) |

Here we render `String` and `Class`, but **when you hover over them**, you can see tooltips for `java.lang.String` and `java.lang.Class`. Although it may not seem a huge added value, it allows for visually compact reports without losing information. And I think it can be useful when there's [two different classes with the same simple name](https://github.com/siom79/japicmp/actions/runs/10546323587#user-content-japicmp.cmp.jararchivecomparator).

@scordio @siom79 Do you guys think we should remove the FQN tooltips, or are they worth keeping?

**Comment by scordio** [comment]
> I'm afraid there's nothing we can do about it; that's standard behavior.

Thanks for the explanation. I see now that it's by GitHub design, and there isn't much to be done here 🙂 

> **when you hover over them**, you can see tooltips

Oh, I honestly didn't spot them before!

> Do you guys think we should remove the FQN tooltips, or are they worth keeping?

I understand the challenge, and the current solution is a good compromise from my point of view. I would keep it.

With this, nothing is left to address 🙂 I'm closing the issue.
