### ISSUE TITLE
japicmp-maven-plugin tries to download plugin dependencies even though skipPomModules is set to true

### ISSUE THREAD

**Issue by rmetzger** [siom79/japicmp#92]
I'm using `japicmp-maven-plugin` in a multi-module project. I've defined the plugin in the root pom.

My plugin definition includes a dependency to a module containing my interface annotations (I haven't found another way to make them available to all the other modules without introducing circular dependencies).

The problem is that the build is failing already with my parent pom because the annotations module is not available.

```
[INFO] --- maven-failsafe-plugin:2.18.1:integration-test (default) @ flink-parent ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- japicmp-maven-plugin:0.6.2-SNAPSHOT:cmp (default) @ flink-parent ---
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/flink/flink-annotations/1.0-SNAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/apache/flink/flink-annotations/1.0-SNAPSHOT/flink-annotations-1.0-SNAPSHOT.jar
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] flink .............................................. FAILURE [  4.008 s]
[INFO] flink-annotations .................................. SKIPPED
[INFO] flink-shaded-hadoop ................................ SKIPPED
[INFO] flink-shaded-hadoop2 ............................... SKIPPED
[INFO] flink-shaded-include-yarn-tests .................... SKIPPED
[INFO] flink-shaded-curator ............................... SKIPPED
[INFO] flink-shaded-curator-recipes ....................... SKIPPED
[INFO] flink-shaded-curator-test .......................... SKIPPED
[INFO] flink-core ......................................... SKIPPED
[INFO] flink-java ......................................... SKIPPED
```

Can we disable the plugin dependency resolution as well when the plugin execution is skipped?

**Comment by siom79** [comment]
Where exactly did you define the dependency on `flink-annotations` (inside the configuration of the `japicmp-maven-plugin` or directly within the root pom)?

The point here is that the maven plugin is annotated with dependency resolution set to `COMPILE`:
```
@Mojo(name = "cmp", requiresDependencyResolution = ResolutionScope.COMPILE, defaultPhase = LifecyclePhase.VERIFY)
public class JApiCmpMojo extends AbstractMojo {
```
This means that all dependencies of the surrounding pom are resolved, such that for most use cases you do not have to list them again inside the japicmp configuration section. Removing this annotation attribute would mean that folks have to list all dependencies of the current artifact again.

Maybe the code that is invoked by this annotation attribute can be invoked directly from the plugin instead...

**Comment by rmetzger** [comment]
I've defined the dependency as a dependency of the plugin, so at the level of the `<plugin>` tag.

I think we could introduce a new configuration value for the plugin to specify the annotation dependency. Then, as you suggested, resolve it directly from the plugin, create a `URLClassloader` and then pass the classloader to the [`Class.forName()` call](https://github.com/siom79/japicmp/blob/develop/japicmp/src/main/java/japicmp/filter/AnnotationClassFilter.java#L14).

If you want I can try to implement the feature.

**Comment by siom79** [comment]
You can already specify dependencies on the plugin level (refer to the bottom of [this page](http://siom79.github.io/japicmp/MavenPlugin.html)):
```
<configuration>
...
	<dependencies>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-math3</artifactId>
			<version>3.4</version>
		</dependency>
	</dependencies>
...
</configuration>
```
This one will be resolved later. The problem here are the dependencies you have added to the enclosingn pom. They are all resolved before our plugin gets invoked. But the [Mojo API Specification](https://maven.apache.org/developers/mojo-api-specification.html) also lists the attribute `requiresDependencyCollection`. Maybe it is possible to only collect them and resolve them after the skip parameter is [evaluated](https://github.com/siom79/japicmp/blob/develop/japicmp-maven-plugin/src/main/java/japicmp/maven/JApiCmpMojo.java#L82).

**Comment by siom79** [comment]
You have set `skip` to `true` in the top level pom, or haven't you? 

You could solve this by using a property like in the following root.pom:
```
<properties>
    <japicmp.plugin.skip>true</japicmp.plugin.skip>
    ...
</properties>
...
<build>
    <plugins>
          <plugin>
		<groupId>com.github.siom79.japicmp</groupId>
		<artifactId>japicmp-maven-plugin</artifactId>
		<version>0.6.1</version>
		<executions>
			<execution>
				<id>single-version</id>
				<phase>pre-integration-test</phase>
				<goals>
					<goal>cmp</goal>
				</goals>
				<configuration>
					<skip>${japicmp.plugin.skip}</skip>
...
```
And in each child pom you can enable the execution:
```
<properties>
    <japicmp.plugin.skip>false</japicmp.plugin.skip>
    ...
</properties>
```

**Comment by siom79** [comment]
As issue [#94](https://github.com/siom79/japicmp/issues/94) shows it really makes sense to add an option that allows users to ignore non-resolvable artifacts. Hence I have just committed a change set that adds the new option `ignoreNonResolvableArtifacts` to the maven artifact.

If you like, you can try it out:
```
git clone https://github.com/siom79/japicmp.git
cd japicmp
git checkout develop
mvn clean install
```

**Comment by rmetzger** [comment]
I didn't know about the `<configuration><dependencies>` option.

I now added it like this:
```xml

<groupId>com.github.siom79.japicmp</groupId>
<artifactId>japicmp-maven-plugin</artifactId>
<version>0.6.2-SNAPSHOT</version>
<configuration>
	<dependencies>
		<dependency>
			<groupId>org.apache.flink</groupId>
			<artifactId>flink-annotations</artifactId>
			<version>${project.version}</version>
		</dependency>
	</dependencies>
</configuration>
```

The error message is now:
```
[ERROR] Failed to execute goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.2-SNAPSHOT:cmp (default) on project flink-core: Execution default of goal com.github.siom79.japicmp:japicmp-maven-plugin:0.6.2-SNAPSHOT:cmp failed: Wrong syntax for exclude option '@org.apache.flink.annotation.PublicExperimental': Could not load 'org.apache.flink.annotation.PublicExperimental': org.apache.flink.annotation.PublicExperimental. Please make sure that all libraries have been added to the classpath or try the option '--ignore-missing-classes'. -> [Help 1]
```
the problem is that ignoring the missing class is not really feasible here

Here, you can find my branch where I'm trying out the plugin, if you want to look into it yourself: https://github.com/rmetzger/flink/tree/flink3129

**Comment by siom79** [comment]
The issue you have is subtle. :smirk: 

You define the plugin in the root pom of your project but you need the annotations from the sub-module flink-annotations. The `Annotation*Filter` in japicmp use a `Class.forName()` call to load this class, but in order for that to work it would have to be on the classpath. But it is not on the classpath, as it isn't added as a normal maven `dependency` in the pom (and can't be added as it hasn't been build when the root pom is evaluated).

Adding the `fline-annotations` module as dependency on the japicmp configuration level, like you have done it, only adds them to the classpath of the class pool used by javassist (and of course not to the classpath of the whole JVM as we would not be able to have separate class paths for the old and new version).

I have just extended the current implementation such that if the `Class.forName()` call fails it tries to use the class pool of javassit to load the class. This way the complete flink build passes without an error.

**Comment by metlos** [comment]
@rmetzger, IMHO, with revapi, you wouldn't have this kind of issue because it doesn't require the classes of the checked jars to be on the classpath of the API checking tool - i.e. it merely "looks" at the classes but doesn't need them to be present in its runtime environment. Btw., may I know the reason why you abandoned revapi? Was that the missing feature you requested, lack of usability, docs or something else?

@siom79, not trying to poach users, @rmetzger has looked at revapi, too ;)

Btw. I've not tried myself, but have you tried your fix with clean local maven repo, @siom79 ? It seems to me that that might be a problem, because the `flink-annotations` module would potentially be unresolvable at the time the root pom would be analyzed by maven...

**Comment by siom79** [comment]
@metlos japicmp does not need all dependencies on the classpath, too. We are talking here about a feature that let's you annotate your API classes such that only these classes are evaluated (filters). And exactly these annotations stem from a submodule that cannot be referenced in the current version from the root pom. It has nothing to do with cleaning the local repository. And revapi would also have to load them from the classpath. :smile:

**Comment by metlos** [comment]
Ok, I will never try to respond to subtle issues like this half asleep again ;) Upon re-reading your conversation I think I finally understand what was going on and how you fixed it.

The point I was trying to make was that in order to match elements by annotations you don't have to have the annotations on the classpath - either that of japicmp or on the classpath of the checked jar. The full annotation class name along with all the values specified are present at the element and therefore the actual class of the annotation gives you no other information (it'd give you the default values of attributes, I guess, but that's not particularly useful in the matching of the annotation, IMHO).

For example, take a look at https://github.com/jboss-javassist/javassist/blob/master/src/main/javassist/CtClassType.java#L455 which checks whether an annotation is present on the class. It doesn't require the annotation class to be present.

**Comment by siom79** [comment]
Yes, you are right. japicmp is doing exactly the same to evaluate annotations without the necessity that the annotation is available on the classpath (see for example [https://github.com/siom79/japicmp/blob/master/japicmp/src/main/java/japicmp/util/AnnotationHelper.java#L81](https://github.com/siom79/japicmp/blob/master/japicmp/src/main/java/japicmp/util/AnnotationHelper.java#L81)).

The `Class.forName()` call was a contribution to the project; but it requires the class to be on the classpath. I pulled the [change set](https://github.com/siom79/japicmp/pull/89) into the project without seeing that this will cause a problem. Yesterday evening I fixed the issue with a workaround, but it should be implemented in a way that does not require the annotation to be present on the classpath.

**Comment by rmetzger** [comment]
> Btw., may I know the reason why you abandoned revapi? Was that the missing feature you requested, lack of usability, docs or something else?

It would have been nicer if you had contacted me privately about this. I think having such conversations at other projects which offer a very similar set of features might be weird for everyone involved. I've requested to connect with you on LinkedIn so that I can send you the reasons over there.

@siom79: Sorry for not passing the Classloader to the `Class.forName()` call. Its the first time I'm working on a maven plugin ;)

Thank you for looking into the issue closely. I'll test it with your latest `develop` branch.

**Comment by rmetzger** [comment]
It seems to work ;) Very nice. Thank you for looking into the issue!

One remark: It might make sense to implement the `toString()` methods for all the filters, otherwise, the report is a bit ugly: `japicmp.filter.AnnotationFieldFilter@4bf25eda;japicmp.filter.AnnotationBehaviorFilter@3a3b8881` ;)

I think we can close this issue.

**Comment by metlos** [comment]
@rmetzger agreed and I hesitated to do that for almost a week :) I don't do social networks too much and so LinkedIn actually didn't occur to me.. Would have been much better than this. Sorry for hijacking this thread a bit @siom79.

**Comment by siom79** [comment]
Long discussions, but I finally found some time to rework the Annotation*Filters such that they now use javassist in order to detect if classes/methods/fields are annotated or not. With these modifications the flink build still is successful and the annotations do not have to be on the class path.

I also implemented the `toString()` on all filters.

Now this feature seems to be finished.
